### ISSUE TITLE
use_async in combination with use_memo

### ISSUE THREAD

**Issue by ctron** [jetli/yew-hooks#25]
I am wondering what the correct approach is to combine `use_async` with `use_memo`. The idea is to only reload when a dependency (passed to `use_memo`) has changed.

**Comment by jetli** [comment]
you can use use_effect_with_deps to depend on something and manually trigger `run()`, like this: https://github.com/jetli/rust-yew-realworld-example-app/blob/77b145bf2e3ba38e43131720f976c6974ded8fb7/crates/conduit-wasm/src/routes/profile.rs#L46

**Comment by ctron** [comment]
Thanks for pointing me into the right direction! I love `yew-hooks`, but it's not always clear to me how to apply hooks. Adding this yo the existing examples would be helpful to me!
