### ISSUE TITLE
cannot use use_interval 

### ISSUE THREAD

**Issue by arcollector** [jetli/yew-hooks#46]
Hello there, I started to use this library, want to use the `use_interval` hook but I'm getting this error

```
the trait bound `impl yew::functional::hooks::Hook<Output = ()> + '_: Hook` is not satisfied
the trait `Hook` is implemented for `BoxedHook<'_, T>
```

I have this simple code

```
#[function_component(Header)]
pub fn header() -> Html {
    let clock = use_state(|| Clock::new());
    {
        let clock = clock.clone();
        use_interval(
            move || {
                clock.set(Clock::new());
            },
            1100,
        );
    }
  
    html! { /* */ }
}
```

it tells me `required by a bound introduced by this call`, could anyone help me, I tried also the example code and I getting the same error :/

**Comment by jetli** [comment]
hi, I cannot reproduce, I can run example app without errors.

**Comment by arcollector** [comment]
ok no problem, may my setup is somehow broken, thank you!
